import logging

def log_ophyd(file_name,__name__):
    """
    The function `log_ophyd` sets up a logger that logs messages to a file with the specified file name.
    @param file_name - The file_name parameter is a string that specifies the name of the log file that
    will be created. This file will store the log messages generated by the logger.
    @param __name__ - The `__name__` parameter is a special built-in variable in Python that represents
    the name of the current module. It is automatically set by Python based on the context in which the
    code is executed.
    @returns a logger object.
    """
    # Set up the logger
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)

    # Create a file handler
    file_handler = logging.FileHandler(file_name)
    file_handler.setLevel(logging.DEBUG)

    # Create a formatter and add it to the file handler
    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    file_handler.setFormatter(formatter)

    # Add the file handler to the logger
    logger.addHandler(file_handler)

    # Disable the Jupyter Notebook default logger
    logger.propagate = False
    return logger